### PR TITLE
Add extra plugin compatibility fail scenario

### PR DESCRIPTION
**Pull request by ghost**
For plugins that state they are compatible with WP4.9 but don't work, it's not always a bug in CP. It may be that a recent plugin update has broken both WP and CP. This has happened a few times now and the plugin dev has been notified and fixed it.

### CODE REVIEW

**Comment by nylen** [comment]
Good suggestion!

>There have also been a few occasions where a plugin update has broken compatibility with both WordPress 4.9.x and ClassicPress; once the plugin developer was made aware of the issue it was quickly rectified.

Can we make this a separate paragraph, and include more details about how to contact plugin developers, in active voice? Maybe something like this?

>There have also been a few occasions where a plugin update has broken compatibility with both WordPress 4.9.x and ClassicPress. Whatever the case may be, we recommend contacting the plugin developers and asking them to make their plugin compatible with WordPress 4.9.x (and therefore ClassicPress).

(We also used to have a template email for this, but it looks like that didn't make it into the FAQs page when we rebuilt the main site: https://www.classicpress.net/faq/)

**Comment by ghost** [comment]
That's fine. Except there's a word missing I think...
>contacting the plugin developers and asking them to make their plugin with WordPress 4.9.x

Make their plugin... work? compatible?

**Comment by nylen** [comment]
Indeed I accidentally a word. I edited my comment after the fact but I meant to put "compatible" there.

**Comment by ghost** [comment]
Sorry, forgot about this. Have added your suggested changes. Also changed 'probably' to 'possibly' in paragraph above.

**Review by nylen — APPROVED** [review]
Looks good to me. Thanks for the PR!

**Pull request merged**
